name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: bundle exec rspec

    - name: Create output directory
      run: mkdir -p ./output/

    - name: Output rendering basic_example as an artifact
      run: ruby examples/basic_example.rb > ./output/basic_example.html

    - name: Output rendering dataset_example as an artifact
      run: ruby examples/dataset_example.rb > ./output/dataset_example.html

    - name: Output rendering dataset_patch as an artifact
      run: ruby examples/dataset_patch.rb > ./output/dataset_patch.html

    - name: Upload example rendering
      uses: actions/upload-artifact@v2
      if: ${{ success() || failure() }}
      with:
        name: example-rendering-ruby-${{ matrix.ruby-version }}
        path: ./output/
