name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: bundle exec rspec

    - name: Create output directory
      run: mkdir -p ./output/

    - name: Output rendering basic_example as an artifact
      run: ruby examples/basic_example.rb > ./output/basic_example.html

    - name: Output rendering basic_example_with_booking as an artifact
      run: ruby examples/basic_example_with_booking.rb > ./output/basic_example_with_booking.html

    - name: Output rendering basic_example_with_booking_minimal as an artifact
      run: ruby examples/basic_example_with_booking_minimal.rb > ./output/basic_example_with_booking_minimal.html

    - name: Output rendering basic_csp_example_with_booking as an artifact
      run: ruby examples/basic_csp_example_with_booking.rb > ./output/basic_csp_example_with_booking.html

    - name: Output rendering dataset_example as an artifact
      run: ruby examples/dataset_example.rb > ./output/dataset_example.html

    - name: Output rendering dataset_example_with_booking as an artifact
      run: ruby examples/dataset_example_with_booking.rb > ./output/dataset_example_with_booking.html

    - name: Output rendering dataset_csp_example_with_booking as an artifact
      run: ruby examples/dataset_csp_example_with_booking.rb > ./output/dataset_csp_example_with_booking.html

    - name: Output rendering dataset_patch as an artifact
      run: ruby examples/dataset_patch.rb > ./output/dataset_patch.html

    - name: Output rendering specific_feed_override_example as an artifact
      run: ruby examples/specific_feed_override_example.rb > ./output/specific_feed_override_example.html

    - name: Output rendering specific_feed_override_example2 as an artifact
      run: ruby examples/specific_feed_override_example2.rb > ./output/specific_feed_override_example2.html

    - name: Upload example renderings
      uses: actions/upload-artifact@v4
      if: ${{ success() || failure() }}
      with:
        name: example-rendering-ruby-${{ matrix.ruby-version }}
        path: ./output/
